title: Remnants of Faerun
description: Information on the "Remnants of Faerun" campaign run by End Initiative
baseurl: ""
url: "https://remnants-of-faerun.end-initiative.com/"
theme: jekyll-theme-modernist

collections:
  content:
    permalink: /:path
